### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by ShiXinBoy** [zh-blogs/.github#2]
请向我们介绍你自己（技术栈、空余时间等等）：

**Comment by linlinzzo** [comment]
放空白交上来，可真有你的。

**Comment by ShiXinBoy** [comment]
那么，加入需要那些要求呢，比如技术方面

**Comment by linlinzzo** [comment]
> 那么，加入需要那些要求呢，比如技术方面

技术组我不知道，地址库维护组要时间相对充裕、吃苦耐劳。

**Comment by ShiXinBoy** [comment]
加入地址库维护需要哪些条件

**Comment by linlinzzo** [comment]
> 加入地址库维护需要哪些条件

你要做非常多的文字工作，访问大量的网站（不下一千个），可能你的复制粘贴键会松掉。加入地址库维护组很苦很苦，你要有心理准备。

**Comment by linlinzzo** [comment]
欸？你是打算加入开往是吗？

**Comment by linlinzzo** [comment]
开往现在有事，等会处理。

**Comment by linlinzzo** [comment]
开往人员已满。
